### ISSUE TITLE
No entries from http server

### ISSUE THREAD

**Issue by biom4st3r** [proconsule/nxmp#4]
I've tried using twisted's web server and pythons built in `http.server`, but nxmp doesn't show any files to open. If I open the server in my desktops browser using it's local ip I can see all the files. 
I know the switch can access the server, because I launched an ftp server which populated just fine.
The http server: https://imgur.com/a/ajbdixl

**Comment by proconsule** [comment]
The http is working only on apache directory listing format.
In the future i will make a parser for other http server also

**Comment by aoleg94** [comment]
https://github.com/proconsule/nxmp/pull/64

**Comment by aoleg94** [comment]
Also you can use my [HTTP server in python](https://gist.github.com/aoleg94/7beb2165a14a090c9fb00e5d0f8446f2), which outputs apache directory listing format and therefore works with NXMP. Note that you need to use port 80 (`sudo python ./nxmp-http-server.py 80`) because NXMP 0.6.2 does not support custon HTTP port numbers/
