### ISSUE TITLE
Play multiple files in a row, Playlist setup is unclear

### ISSUE THREAD

**Issue by Mom19** [proconsule/nxmp#66]
Hello, first off I want to thank you guys for making this awesome homebrew. Been using pplay until I found NXMP and switched to NXMP ever since.

But I currently dont know or understand how I can add multiple videos/music files into a playlist? I've been playing files one by one so far, but in the long run, especially with big music folders its a bit of a problem. Im probably just missing something here :D

Idk if this is implemented yet or not, but if it is and I just didn't figure out how to, please update the readme

Thank you so much for your efforts <3

**Comment by andercard0** [comment]
> Hello, first off I want to thank you guys for making this awesome homebrew. Been using pplay until I found NXMP and switched to NXMP ever since.
> 
> But I currently dont know or understand how I can add multiple videos/music files into a playlist? I've been playing files one by one so far, but in the long run, especially with big music folders its a bit of a problem. Im probably just missing something here :D
> 
> Idk if this is implemented yet or not, but if it is and I just didn't figure out how to, please update the readme
> 
> Thank you so much for your efforts <3

In order to make a playlist properly, you'll need: 
1. Inside of the folder you have all your medias press D-pad to the left you'll notice that a [ ] box appears
2. Press down to highlight mentioned media and then press A buttom to confirm.
3. Do the same process for the other medias you have in this folder
4. Finally, press Y until you return to home screen
5. Choose playlist option there'll be all medias
6. Play.

Problem with this method is, the  playlist isn't record after you close the application.
